### ISSUE TITLE
JSON Not created correctly

### ISSUE THREAD

**Issue by mattnield** [jsdaniell/create-json#9]
I tried creating a simple JSON file with the following content:
```json
{
  "auth": {
    "user": "",
    "password": ""
  }
}
```
To do this I created a repository variable containing the above JSON and then tried to call it in my deploy job. This is for a .NET application and looks as follows:
```yaml
      - name: Create App Settings
        id: create-json
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: 'appsettings.json'
          json: ${{ vars.APP_SETTINGS }}
```
What I see being created though is a file that looks like this:
```text
auth:
 user:
 password:
```

What's causing this formatting issue?
